import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Carousel from "../components/Carousel";
import "react-responsive-carousel/lib/styles/carousel.min.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Drinks Food Life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Carousel />
      </div>

      <div className={styles.submain}>
        <p> We miss Loic and Will!</p> <p> We miss Loic and Will!</p>
        <p> We miss Loic and Will!</p>
        <p> We miss Loic and Will!</p>
        <p> We miss Loic and Will!</p>
        <p> We miss Loic and Will!</p>
      </div>
      <div className={styles.submain}>
        <p>Chicken is a Chicken</p>
      </div>
    </div>
  );
}
