"use client";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Layout.module.css";
import ContentCard from "../(components)/ContentCard"; 
import headerStyles from "../styles/Header.module.css";
import RevolvingGLBPage from '../(components)/Logo3D';
export default function Home() {
  return (
    <>
    <body>
      <Head>
        <title>About </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
     
        <div className={styles.article1}>
    
          <p className={headerStyles.description}>
    
            {/* <div className="image-wrapper">
              {/* <Image
                alt="Party"
                width={500}
                height={500}
                src="https://res.cloudinary.com/adamaslan/image/upload/v1654725062/drinksfoodlife/amaro-monte_omsl1h.jpg"
              />{" "}
            </div> */} 
          </p>
          <p>Drinks Food Life is a tech-forward media company based in New York City. Leveraging API development and AI pipelines, DFL is always looking for the next avenue to disrupt traditional media in the attention economy. </p>
          <br /> <br /> 
          {/* className="revolving-glb-container" */}
<p>Drag and interact with our custom 3D logo! Looking to add some pop to your website? Wanting to integrate more AI into your business? Let us help you. We have solutions for businesses with 1 to 10000 employees! Email us at drinksfoodlife@gmail.com or contact us on instagram @drinksfoodlife</p>

          <p>
          <RevolvingGLBPage glbFile="/dfl-loading3.glb"     style={{ width: '90%', height: '70vh'}} />

  Founded with a desire to focus on drinks and food, the project quickly evolved as life—in its most general yet effervescent spirit—began to pour through. Soon came articles on Frida, on Botanical Gardens, on Skiing, and even on Spear Fishing! What began as a niche exploration has grown into a vibrant mosaic of culture, curiosity, and lived experience.
</p>
<p>
  We’ve been fortunate to feature contributions from @chemixtry, @journeyswithjaphe, Loic Luspo, @omlettehoe, @cosmicveggie, and others, each bringing their unique voice and perspective to the mix.
</p>
          <h4>
            Please follow us on Instagram{" "}
            <a
                href="https://www.instagram.com/drinksfoodlife/?hl=en"
                target="_blank"
                rel="noopener noreferrer"
            >
              <u>HERE</u>
            </a>
          </h4>
        </div>
      </div>
      <ContentCard />
      </body>
    </>
  );
}
