import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Layout.module.css";
import ContentCard from "../components/ContentCard";
import headerStyles from "../styles/Header.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>About </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.article1}>
          <p className={headerStyles.description}>
            About Drinks Food Life
            <div className="image-wrapper">
              <Image
                alt="Party"
                width={500}
                height={500}
                src="https://res.cloudinary.com/adamaslan/image/upload/v1654725062/drinksfoodlife/amaro-monte_omsl1h.jpg"
              />{" "}
            </div>
          </p>
          <br />


          <p>
            Founded with the desire to focus on drinks and food, but then life
            in its most general yet effervescent spirit came through. We have
            had contributions from @chemixtry, @journeyswithjaphe , Loic Luspo,
            @omlettehoe, @cosmicveggie and others.
          </p>
          <h4>
            Please follow us on Instagram{" "}
            <a
                href="https://www.instagram.com/drinksfoodlife/?hl=en"
                target="_blank"
                rel="noopener noreferrer"
            >
              <u>HERE</u>
            </a>
          </h4>
        </div>
      </div>
      <ContentCard />
    </>
  );
}
