import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Layout.module.css";
import ContentCard from "../components/ContentCard";
import headerStyles from "../styles/Header.module.css";
import RevolvingGLBPage from '../components/Logo3D';
export default function Home() {
  return (
    <>
      <Head>
        <title>About </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
     
        <div className={styles.article1}>
        <RevolvingGLBPage glbFile="/dfl-loading3.glb"  style={{ width: '90%', height: '70vh'}} />
          <p className={headerStyles.description}>
    
            {/* <div className="image-wrapper">
              {/* <Image
                alt="Party"
                width={500}
                height={500}
                src="https://res.cloudinary.com/adamaslan/image/upload/v1654725062/drinksfoodlife/amaro-monte_omsl1h.jpg"
              />{" "}
            </div> */} 
          </p>
          <br />
<p>Looking to add some pop to your website? Let us help you! Email us at drinksfoodlife@gmail.com or contact us on instagram @drinksfoodlife</p>

<p>We started Drinks Food Life with a love of cocktails and spirits and then soon saw how food and all of life come together in this process. We love telling some of life’s most interesting stories, whether it be about visiting micro mezcal distilleries in rural Oaxaca, our ongoing passion for learning about spirits that come from the US and every other corner of the world, or all the beautiful places and culture we encounter along the way.</p>
          <p>
            Find life in its most appreciative and effervescent spirit via our articles on Frida, on Botanical Gardens, on Skiing, and even on Spear Fishing!  
          </p>
          <p>To advertise with us contact: ads@drinksfoodlife.com</p>
          <p>To pitch an article to us contact: editor@drinksfoodlife.com</p>
          <p>Many thanks to our team who have been involved in the process with contributions from @chemixtry, @journeyswithjaphe , Loic Luspo,
            @omlettehoe, @cosmicveggie, @adameatsanddrinkswell, our assitant editor Cassidy Boch, and others.</p>
            
          <h4>
            Please follow us on Instagram{" "}
            <a
                href="https://www.instagram.com/drinksfoodlife/?hl=en"
                target="_blank"
                rel="noopener noreferrer"
            >
              <u>HERE</u>
            </a>
          </h4>
        </div>
      </div>
      <ContentCard />
    </>
  );
}
