import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Layout.module.css";
import ContentCard from "../components/ContentCard";

import headerStyles from "../styles/Header.module.css";

export default function Home() {
  return (
    <>
      <Head>
        git
        <title>On the Art and Spear Fishing of Nicole Burko</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.article1}>
          <br />
          <p className={headerStyles.description}>
            On Art and Spear Fishing <br />
            <Image
              alt="fish plate"
              className="fish2.jpg"
              width={872}
              height={554}
              src="/fish.jpg"
            />{" "}
          </p>
          <p>
            My friend caught a fish free diving in the depths of the Atlantic
            like a ferocious predator, but photos of her submerged laying in
            wait at the bottom of the sea are more precious and beautiful than
            anything else. How nice it is to know that this blackened strip bass
            came from the hands of a friend, Nicole Burko. Check out her art
            here @nicoleburko on insta. Also noteworthy, fried plantains
            forever, pescatarian vibes, and new favourite green -> Baby Kale.
            Not that I don’t love my arugula and red lettuce, but that baby kale
            has the cutest name of the leafy greens that I know of. Is their
            cuter leafy green competition?
          </p>
        </div>
      </div>
      <div className="wrapper">
        <a href="./amaromontenegro">
          <ContentCard
            img="https://lh3.googleusercontent.com/SpfSt4EadOjpRUZCfjEPu_bl5mCTyXq5skTyHKKqwcCt1hUzXHZ5ZxU9rPg_oY4e_tIZQQnZb4RD4FjBFzJTmMGKArLmctic3R1oD7GbBy_kXHazlVy1QdGWiN0ywz1GGenQRrCl2w=w2400"
            title="Drinking Amaros at ZXY Gallery"
            description="Amaro Montenegro making an appearance at ZXY Gallery"
            tag="amaromontenegro"
            href="amaromontenegro"
          />
        </a>

        <a href="./northdumpling">
          <ContentCard
            img="https://images.unsplash.com/photo-1529928520614-7c76e2d99740?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ"
            title="North Dumpling"
            description="In love with North Dumpling "
            href="northdumpling"
          />
        </a>
      </div>
      <div className={styles.smain}>
        Contact us cause this is now the footer
      </div>
    </>
  );
}
