import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Layout.module.css";
import ContentCard from "../components/ContentCard";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Drinks Food Life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <div className={styles.cards}>
        <Link href="/artandfish">
          <div className={styles.card}>
            <Image
              alt="fish"
              width={500}
              height={500}
              src="https://res.cloudinary.com/adamaslan/image/upload/v1654729613/drinksfoodlife/fish_ddrxgr.jpg"
            />{" "}
            <h2> On Art and Spear Fishing</h2> <h3>The Nicole Burko Story</h3>
          </div>
        </Link>

        <Link href="/northdumpling">
          <div className={styles.card}>
            <Image
              alt="dumpling"
              className="img2"
              width={500}
              height={500}
              src="https://res.cloudinary.com/adamaslan/image/upload/v1654718488/drinksfoodlife/northdump1_dptuen.jpg"
            />{" "}
            <h2> North Dumpling, my Guru</h2>{" "}
            <h3>I'm in love with North Dumpling, duh.</h3>
          </div>
        </Link>

        <Link href="/naturalwine">
          <div className={styles.card}>
            <Image
              alt="wine"
              className="img2"
              width={500}
              height={500}
              src="https://res.cloudinary.com/adamaslan/image/upload/v1654718485/drinksfoodlife/coup-wine_pjdgdv.jpg"
            />{" "}
            <h2> An Awkward Quest</h2> <h3>For a Funky Natural Red</h3>
          </div>
        </Link>

        <Link href="/cafeversailles" passHref>
          <div className={styles.card}>
            <Image
              alt="Cafe Versailles"
              className="img2"
              width={500}
              height={500}
              src="https://res.cloudinary.com/adamaslan/image/upload/v1654726367/drinksfoodlife/versailles_h25q20.jpg"
            />{" "}
            <h2> In Love with Cafe Versailles</h2>
            <h3>Especially the MIA airport location</h3>
          </div>
        </Link>
      </div>
      <div className="wrapper">
        {/* sticky social and tiny about + newsletter */}
        <a href="./amaromontenegro">
          <ContentCard
            img="https://res.cloudinary.com/adamaslan/image/upload/v1654725062/drinksfoodlife/amaro-monte_omsl1h.jpg"
            title="Drinking Amaros at ZXY Gallery"
            description="Amaro Montenegro making an appearance at ZXY Gallery"
            tag="amaromontenegro"
            href="amaromontenegro"
          />
        </a>

        <a href="./northdumpling">
          <ContentCard
            img="https://res.cloudinary.com/adamaslan/image/upload/v1654718487/drinksfoodlife/teasecret1_corwi6.jpg"
            title="Tea Love'"
            description="We Love Tea, for real"
            href="northdumpling"
          />
        </a>
        <a href="./amaromontenegro">
          <ContentCard
            img="https://res.cloudinary.com/adamaslan/image/upload/v1654725062/drinksfoodlife/amaro-monte_omsl1h.jpg"
            title="Drinking Amaros at ZXY Gallery"
            description="Amaro Montenegro making an appearance at ZXY Gallery"
            tag="amaromontenegro"
            href="amaromontenegro"
          />
        </a>

        <a href="./northdumpling">
          <ContentCard
            img="https://images.unsplash.com/photo-1529928520614-7c76e2d99740?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ"
            title="Tea Love"
            description="Tea Shopping at Puerto Rico"
            href="tea"
          />
        </a>
      </div>
      <Link href="/babydaddy">
        <div className={styles.card2}>
          <Image
            src="https://res.cloudinary.com/adamaslan/image/upload/v1654724665/drinksfoodlife/babydaddy_bkw67t.jpg"
            width={500}
            height={500}
            alt="beer"
          />
          <h2>Baby Daddy Please</h2> <h3>Baby Daddy is a great choice</h3>
        </div>
      </Link>
      <Link href="/mole">
        <div className={styles.card2}>
          <Image
            alt="mole"
            className="img2"
            width={500}
            height={500}
            src="/mole.jpg"
          />{" "}
          <h2> On the Love of Mole and Coyoacan</h2>{" "}
          <h3>Fida, Mole, Coyoacan Oh MY!</h3>
        </div>
      </Link>
    </>
  );
}
