import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Layout.module.css";
import ContentCard from "../components/ContentCard";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Drinks Food Life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <div className={styles.cards}>
        <Link href="/artandfish">
          <div className={styles.card}>
            <Image
              alt="fish"
              width={500}
              height={500}
              src="https://res.cloudinary.com/adamaslan/image/upload/v1654729613/drinksfoodlife/fish_ddrxgr.jpg"
            />{" "}
            <h2> On Art and Spear Fishing</h2> <h3>The Nicole Burko Story</h3>
          </div>
        </Link>

        <Link href="/northdumpling">
          <div className={styles.card}>
            <Image
              alt="dumpling"
              className="img2"
              width={500}
              height={500}
              src="https://res.cloudinary.com/adamaslan/image/upload/v1654718488/drinksfoodlife/northdump1_dptuen.jpg"
            />{" "}
            <h2> North Dumpling, my Guru</h2>{" "}
            <h3>I'm in love with North Dumpling, duh.</h3>
          </div>
        </Link>

        <Link href="/naturalwine">
          <div className={styles.card}>
            <Image
              alt="wine"
              className="img2"
              width={500}
              height={500}
              src="https://res.cloudinary.com/adamaslan/image/upload/v1654718485/drinksfoodlife/coup-wine_pjdgdv.jpg"
            />{" "}
            <h2> An Awkward Quest</h2> <h3>For a Funky Natural Red</h3>
          </div>
        </Link>

        <Link href="/cafeversailles" passHref>
          <div className={styles.card}>
            <Image
              alt="Cafe Versailles"
              className="img2"
              width={500}
              height={500}
              src="https://res.cloudinary.com/adamaslan/image/upload/v1654726367/drinksfoodlife/versailles_h25q20.jpg"
            />{" "}
            <h2> In Love with Cafe Versailles</h2>
            <h3>Especially the MIA airport location</h3>
          </div>
        </Link>
      </div>
      <ContentCard />
      <Link href="/babydaddy">
        <div className={styles.card2}>
          <Image
            src="https://res.cloudinary.com/adamaslan/image/upload/v1654731696/drinksfoodlife/babydaddy2_u29dmu.png"
            width={500}
            height={500}
            alt="beer"
          />
          <h2>Baby Daddy Please</h2> <h3>Baby Daddy is a great choice</h3>
        </div>
      </Link>
      <Link href="/mole" passHref>
        <div className={styles.card2}>
          <Image
            alt="mole"
            className="img2"
            width={500}
            height={500}
            src="/mole.jpg"
          />{" "}
          <h2> On the Love of Mole and Coyoacan</h2>{" "}
          <h3>Fida, Mole, Coyoacan Oh MY!</h3>
        </div>
      </Link>
    </>
  );
}
