import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Layout.module.css";
import ContentCard from "../components/ContentCard";

export default function Home() {
  return ( <
    >
    <
    div className = {
      styles.container
    } >
    <
    Head >
    <
    title > Drinks Food Life < /title> <
    meta name = "description"
    content = "Generated by create next app" / >
    <
    link rel = "icon"
    href = "/favicon.ico" / >
    <
    /Head> <
    div className = {
      styles.main
    } > < /div> <
    div className = {
      styles.submain
    } >
    <
    p >
    North Dumpling you are the most beautiful dumpling spot and you dont even know it.I follow the directions
    for your frozen dumplings that you pasted on to the glass display next to the spring rolls seemingly years ago.Eternal endless bliss pours through your dumplings.Bountiful is the vitality of the owners ps. <
    /p> <
    /div>

    <
    div className = {
      styles.smain
    } >
    <
    div >
    <
    Image
    alt = "dumpling"
    className = "img2" 
    width = {
      500
    }
    height = {
      500
    }
    src = "/northdump1.jpg" / > {
      " "
    } <
    /div> <
    div className= {styles.divArt} > < h1 > Delicious Dumplings < /h1> <h2>Why are they so gooood? </h2 > < /div>

    <
    /div> <
    div className = {
      styles.smain3
    } >
    <
    p >
    Here 's is another section its important we need more content why? I
    thinking its a visual thing.Cards, Carousel, some animation, some hover effects.These are things that make something seem professional. <
    /p> <
    /div> <
    /div> <
    div className = "wrapper" >
    <
    a href = "./amaromontenegro" >
    <
    ContentCard img = "https://lh3.googleusercontent.com/SpfSt4EadOjpRUZCfjEPu_bl5mCTyXq5skTyHKKqwcCt1hUzXHZ5ZxU9rPg_oY4e_tIZQQnZb4RD4FjBFzJTmMGKArLmctic3R1oD7GbBy_kXHazlVy1QdGWiN0ywz1GGenQRrCl2w=w2400"
    title = "Drinking Amaros at ZXY Gallery"
    description = "Amaro Montenegro making an appearance at ZXY Gallery"
    tag = "amaromontenegro"
    href = "amaromontenegro" /
    >
    <
    /a>

    <
    a href = "./northdumpling" >
    <
    ContentCard img = "https://images.unsplash.com/photo-1529928520614-7c76e2d99740?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ"
    title = "North Dumpling"
    description = "In love with North Dumpling "
    href = "northdumpling" /
    >
    <
    /a> <
    /div> <
    />
  );
}
